import React, { useState, useEffect } from 'react';
import { Helmet } from 'react-helmet';
import axios from "axios";
import '../../styles/fonts.css';
import '../../App.css';
import styles from './Home.module.css';
import InputField from './InputField/inputField';
import Result from './Result/result';
import Navbar from './Navbar/Navbar';
import PremiumBadge from '../Components/BuyPremium/Buypremium'; // Import the PremiumBadge component
import Proof from '../Proof/proof';
import Footer from '../Footer/footer';
import WhyPremium from '../Whypremium.js/whypremium';
import TestimonialsSection from '../Testimonials/TestimonialsSection';

const Home = () => {
  const [resultData, setResultData] = useState(null);
  const [isBig, setisBig] = useState(false);
  const initialEmail = localStorage.getItem("email");
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (initialEmail) {
      authEmail(initialEmail);
    }
  }, [initialEmail]);

  const authEmail = async (email) => {
    setIsLoading(true);
    const requestBody = { email: email };
    try {
      var response = await axios.post("https://flask-hello-world-theta-green.vercel.app/auth", requestBody);
      console.log("POST request successful");
      console.log(response.data.premium);
      if (response.data.premium === true) {
        localStorage.setItem('premium', 'true');
        window.location.reload();
      }
      setIsLoading(false);
    } catch (error) {
      console.log("Error occurred while making POST request:", error);
      setIsLoading(false);
      window.location.reload();
    }
  }

  return (
    <div>
      <Helmet>
        <meta
          name="keywords"
          content="... (your meta tags)"
        />
        {/* Add any other meta tags as needed */}
      </Helmet>
      <Navbar />

      <div className={styles['home-main']}>
        <div className={styles['home-heading-description-div']}>
          <div className={styles['home-heading']}>
            Cheat<span style={{ color: 'pink' }}>GPT</span>!
          </div>

          <div className={styles['home-description']}>
            <h1>
              The ultimate AI detection bypass tool. We remove AI detection from
              content generated by ChatGPT and other AI language models.
            </h1>
          </div>
        </div>
        <InputField setResultData={setResultData} setisBig={setisBig} />
        <div className={styles['home-full-result']}>
          {isLoading && <div>Loading...</div>}
          {resultData && <Result data={resultData} />}
          {isBig && <PremiumBadge />} {/* Use the PremiumBadge component here */}
        </div>
      </div>
      <Proof />
      <WhyPremium />
      <TestimonialsSection />
      <Footer />
    </div>
  );
};

export default Home;
