import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import '../../styles/fonts.css';
import '../../App.css';
import styles from './Home.module.css';
import InputField from './InputField/inputField';
import Result from './Result/result';
import Navbar from './Navbar/Navbar';
import About from './About/About';
import Payment from '../Payment/Payment';
import PremiumBadge from '../Components/BuyPremium/Buypremium'; // Import the PremiumBadge component
import Proof from '../Proof/proof';
import Footer from '../Footer/footer';
import WhyPremium from '../Whypremium.js/whypremium';
import Testimonials from '../Testimonials/TestimonialsSection';
import TestimonialsSection from '../Testimonials/TestimonialsSection';

const Home = () => {
  const [resultData, setResultData] = useState(null);
  const [isBig, setisBig] = useState(false);

  return (
    <div>
      <Helmet>
        {/* ... (Helmet content remains the same) ... */}
      </Helmet>
      <Navbar />

      <div className={styles['home-main']}>
        <div className={styles['home-heading-description-div']}>
          <div className={styles['home-heading']}>
            Cheat<span style={{ color: 'pink' }}>GPT</span>!
          </div>

          <div className={styles['home-description']}>
            <h1>
              The ultimate AI detection bypass tool. We remove AI detection from
              content generated by ChatGPT and other AI language models.
            </h1>
          </div>
        </div>
        <InputField setResultData={setResultData} setisBig={setisBig} />
        <div className={styles['home-full-result']}>
          {resultData && <Result data={resultData} />}
          {isBig && <PremiumBadge />} {/* Use the PremiumBadge component here */}
        </div>
      </div>
      {/* <Payment/> */}
      {/* <Proof/>
      <WhyPremium/>
      // <TestimonialsSection/> */}
      <TestimonialsSection/>
      {/* <Footer/> */}
    </div>
  );
};

export default Home;
