import React, { useState } from "react";
import { Helmet } from "react-helmet";
import "../../styles/fonts.css";
import "../../App.css";
import styles from "./Home.module.css";
import InputField from "./InputField/inputField";
import Result from "./Result/result";
import Navbar from "./Navbar/Navbar";
import About from "./About/About";

const Home = () => {
  const [resultData, setResultData] = useState(null);

  return (
    <div>
      <Helmet>
        <title>Bypass AI Detection | CheatGPT</title>
        <meta
          name="description"
          content="The ultimate AI detection bypass tool. We remove AI detection from content generated by ChatGPT and other AI language models."
        />
        <meta
          name="keywords"
          content="AI detection bypass,AI detection removal,Content generated by AI,ChatGPT content,Language model detection,AI language model bypass,AI content filtering,AI text manipulation,Anti-detection solutions,
          Bypassing AI filters,Content moderation bypass,Natural language processing,Unrestricted AI content,AI-generated text privacy,Chatbot content filtering,Text manipulation techniques,Evading language model detection,AI content censorship,Digital content privacy,AI-generated content control"
        />
      </Helmet>
      <Navbar />

      <div className={styles["home-main"]}>
        <div className={styles["home-heading-description-div"]}>
          <div className={styles["home-heading"]}>
            Cheat<span style={{ color: "pink" }}>GPT</span>!
          </div>

          <div className={styles["home-description"]}>
            <h1>
            The ultimate AI detection bypass tool. We remove AI detection from
            content generated by ChatGPT and other AI language models.
            </h1>
        
          </div>
        </div>
        <InputField setResultData={setResultData} />
        {resultData && <Result data={resultData} />}
      </div>
    </div>
  );
};

export default Home;
