import React from "react";
import { Route, Routes, Navigate } from "react-router-dom";
import { Helmet } from "react-helmet";
import AuthContext from "./store/authContext";
import "./styles/fonts.css";
import "./App.css";
import Home from "./pages/Home/Home";
import Stats from "./pages/Stats/stats";
import Payment from "./pages/Payment/Payment";
import GivePremium from "./pages/GivePremium/givepremium";

const App = () => {
  return (
    <div>
      <Helmet>
        <title>Bypass AI Detection | CheatGPT</title>
        <meta
          name="description"
          content="The ultimate AI detection bypass tool. We remove AI detection from content generated by ChatGPT and other AI language models."
        />
        <meta
          name="keywords"
          content="AI detection bypass,AI detection removal,Content generated by AI,ChatGPT content,Language model detection,AI language model bypass,AI content filtering,AI text manipulation,Anti-detection solutions,
Bypassinng AI filters,Content moderation bypass,Natural language processing,Unrestricted AI content,AI-generated text privacy,Chatbot content filtering,Text manipulation techniques,Evading language model detection,AI content censorship,Digital content privacy,AI-generated content control"
        />
      </Helmet>
      <Routes>
        <Route path="/" element={<Navigate to="home" />} />
        <Route path="stats" element={<Stats />} />
        <Route path="home" element={<Home />} />
        <Route path="payment" element={<Payment />} />
        <Route path="givepremium" element={<GivePremium/>} />
      </Routes>
    </div>
  );
};

export default App;
